


all: example1 example3 example4 example5

example1: example1.c
	$(CC) -o example1 -O -I../src ../src/libMVL.c example1.c 
	
example3: example3.c
	$(CC) -o example3 -O -I../src ../src/libMVL.c example3.c 

example4: example4.c
	$(CC) -o example4 -O -I../src ../src/libMVL.c example4.c 
	
example5: example5.c
	$(CC) -o example5 -O -I../src ../src/libMVL.c example5.c 
